In [184]:
import sympy as sp
import numpy as np
import math

In [185]:
def fid(i,j):
    return (i+1)*3+j+1

def oid(a,b):
    return a*3+b

In [186]:
f = np.ndarray(9, dtype=object)
for i in range(9):
    f[i] = sp.Symbol(f'f[{i}]')


In [187]:
m = np.ndarray(9, dtype=object)
for i in range(9):
    m[i] = sp.Symbol(f'm[{i}]')

In [188]:
M = np.zeros((9,9), dtype=int)
for a in range(3):
    for b in range(3):
        for i in {-1,0,1}:
            for j in {-1,0,1}:
                M[oid(a,b),fid(i,j)] = (i**a)*(j**b)
Mi = np.linalg.inv(M)
Mi

array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.25, -0.25,  0.  , -0.25,  0.25],
       [ 0.  ,  0.  ,  0.  , -0.5 ,  0.  ,  0.5 ,  0.5 ,  0.  , -0.5 ],
       [ 0.  ,  0.  ,  0.  ,  0.  , -0.25, -0.25,  0.  ,  0.25,  0.25],
       [ 0.  , -0.5 ,  0.5 ,  0.  ,  0.  ,  0.  ,  0.  ,  0.5 , -0.5 ],
       [ 1.  ,  0.  , -1.  ,  0.  ,  0.  ,  0.  , -1.  ,  0.  ,  1.  ],
       [ 0.  ,  0.5 ,  0.5 ,  0.  ,  0.  ,  0.  ,  0.  , -0.5 , -0.5 ],
       [ 0.  ,  0.  ,  0.  ,  0.  , -0.25,  0.25,  0.  , -0.25,  0.25],
       [ 0.  ,  0.  ,  0.  ,  0.5 ,  0.  , -0.5 ,  0.5 ,  0.  , -0.5 ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.25,  0.25,  0.  ,  0.25,  0.25]])

In [189]:
M

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1],
       [-1,  0,  1, -1,  0,  1, -1,  0,  1],
       [ 1,  0,  1,  1,  0,  1,  1,  0,  1],
       [-1, -1, -1,  0,  0,  0,  1,  1,  1],
       [ 1,  0, -1,  0,  0,  0, -1,  0,  1],
       [-1,  0, -1,  0,  0,  0,  1,  0,  1],
       [ 1,  1,  1,  0,  0,  0,  1,  1,  1],
       [-1,  0,  1,  0,  0,  0, -1,  0,  1],
       [ 1,  0,  1,  0,  0,  0,  1,  0,  1]])

In [190]:
M@f

array([f[0] + f[1] + f[2] + f[3] + f[4] + f[5] + f[6] + f[7] + f[8],
       -f[0] + f[2] - f[3] + f[5] - f[6] + f[8],
       f[0] + f[2] + f[3] + f[5] + f[6] + f[8],
       -f[0] - f[1] - f[2] + f[6] + f[7] + f[8],
       f[0] - f[2] - f[6] + f[8], -f[0] - f[2] + f[6] + f[8],
       f[0] + f[1] + f[2] + f[6] + f[7] + f[8],
       -f[0] + f[2] - f[6] + f[8], f[0] + f[2] + f[6] + f[8]],
      dtype=object)

In [191]:
Mi@m

array([0.25*m[4] - 0.25*m[5] - 0.25*m[7] + 0.25*m[8],
       -0.5*m[3] + 0.5*m[5] + 0.5*m[6] - 0.5*m[8],
       -0.25*m[4] - 0.25*m[5] + 0.25*m[7] + 0.25*m[8],
       -0.5*m[1] + 0.5*m[2] + 0.5*m[7] - 0.5*m[8],
       1.0*m[0] - 1.0*m[2] - 1.0*m[6] + 1.0*m[8],
       0.5*m[1] + 0.5*m[2] - 0.5*m[7] - 0.5*m[8],
       -0.25*m[4] + 0.25*m[5] - 0.25*m[7] + 0.25*m[8],
       0.5*m[3] - 0.5*m[5] + 0.5*m[6] - 0.5*m[8],
       0.25*m[4] + 0.25*m[5] + 0.25*m[7] + 0.25*m[8]], dtype=object)

In [192]:
k = np.ndarray(9, dtype=object)
for i in range(9):
    k[i] = sp.Symbol(f'k[{i}]')
kt = np.ndarray(9, dtype=object)
u, v = sp.symbols('u v')
for a in range(3):
    for beta in range(3):
        sum = 0
        for b in range(beta+1):
            sum += math.comb(beta, b)*(-v)**(beta - b)*m[oid(a,b)]
        kt[oid(a,beta)] = sum
for alpha in range(3):
    for beta in range(3):
        sum = 0
        for a in range(alpha+1):
            sum += math.comb(alpha, a)*(-u)**(alpha - a)*kt[oid(a,beta)]
        k[oid(alpha,beta)] = sum
k


array([m[0], -m[0]*v + m[1], m[0]*v**2 - 2*m[1]*v + m[2], -m[0]*u + m[3],
       -m[3]*v + m[4] - u*(-m[0]*v + m[1]),
       m[3]*v**2 - 2*m[4]*v + m[5] - u*(m[0]*v**2 - 2*m[1]*v + m[2]),
       m[0]*u**2 - 2*m[3]*u + m[6],
       -m[6]*v + m[7] + u**2*(-m[0]*v + m[1]) - 2*u*(-m[3]*v + m[4]),
       m[6]*v**2 - 2*m[7]*v + m[8] + u**2*(m[0]*v**2 - 2*m[1]*v + m[2]) - 2*u*(m[3]*v**2 - 2*m[4]*v + m[5])],
      dtype=object)

In [193]:
k_ = np.ndarray(9, dtype=object)
for i in range(9):
    k_[i] = sp.Symbol(f'k[{i}]')
mt_ = np.ndarray(9, dtype=object)
m_ = np.ndarray(9, dtype=object)
for a in range(3):
    for beta in range(3):
        sum = 0
        for b in range(beta+1):
            sum += math.comb(beta, b)*(v)**(beta - b)*k_[oid(a,b)]
        mt_[oid(a,beta)] = sum
for alpha in range(3):
    for beta in range(3):
        sum = 0
        for a in range(alpha+1):
            sum += math.comb(alpha, a)*(u)**(alpha - a)*mt_[oid(a,beta)]
        m_[oid(alpha,beta)] = sum

m_

array([k[0], k[0]*v + k[1], k[0]*v**2 + 2*k[1]*v + k[2], k[0]*u + k[3],
       k[3]*v + k[4] + u*(k[0]*v + k[1]),
       k[3]*v**2 + 2*k[4]*v + k[5] + u*(k[0]*v**2 + 2*k[1]*v + k[2]),
       k[0]*u**2 + 2*k[3]*u + k[6],
       k[6]*v + k[7] + u**2*(k[0]*v + k[1]) + 2*u*(k[3]*v + k[4]),
       k[6]*v**2 + 2*k[7]*v + k[8] + u**2*(k[0]*v**2 + 2*k[1]*v + k[2]) + 2*u*(k[3]*v**2 + 2*k[4]*v + k[5])],
      dtype=object)

In [194]:
sp.simplify(m_)

[k[0], k[0]*v + k[1], k[0]*v**2 + 2*k[1]*v + k[2], k[0]*u + k[3], k[3]*v + k[4] + u*(k[0]*v + k[1]), k[3]*v**2 + 2*k[4]*v + k[5] + u*(k[0]*v**2 + 2*k[1]*v + k[2]), k[0]*u**2 + 2*k[3]*u + k[6], k[6]*v + k[7] + u**2*(k[0]*v + k[1]) + 2*u*(k[3]*v + k[4]), k[6]*v**2 + 2*k[7]*v + k[8] + u**2*(k[0]*v**2 + 2*k[1]*v + k[2]) + 2*u*(k[3]*v**2 + 2*k[4]*v + k[5])]