In [143]:
import sympy as sp
import numpy as np
import math

In [144]:
def fid(i,j):
    return (i+1)*3+j+1

def oid(a,b):
    return a*3+b

In [145]:
f = np.ndarray(9, dtype=object)
for i in range(9):
    f[i] = sp.Symbol(f'f[{i}]')


In [146]:
m = np.ndarray(9, dtype=object)
for i in range(9):
    m[i] = sp.Symbol(f'm[{i}]')

In [147]:
M = np.zeros((9,9), dtype=int)
for a in range(3):
    for b in range(3):
        for i in {-1,0,1}:
            for j in {-1,0,1}:
                M[oid(a,b),fid(i,j)] = (i**a)*(j**b)
M

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1],
       [-1,  0,  1, -1,  0,  1, -1,  0,  1],
       [ 1,  0,  1,  1,  0,  1,  1,  0,  1],
       [-1, -1, -1,  0,  0,  0,  1,  1,  1],
       [ 1,  0, -1,  0,  0,  0, -1,  0,  1],
       [-1,  0, -1,  0,  0,  0,  1,  0,  1],
       [ 1,  1,  1,  0,  0,  0,  1,  1,  1],
       [-1,  0,  1,  0,  0,  0, -1,  0,  1],
       [ 1,  0,  1,  0,  0,  0,  1,  0,  1]])

In [148]:
Mi = np.linalg.inv(M)
Mi

array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.25, -0.25,  0.  , -0.25,  0.25],
       [ 0.  ,  0.  ,  0.  , -0.5 ,  0.  ,  0.5 ,  0.5 ,  0.  , -0.5 ],
       [ 0.  ,  0.  ,  0.  ,  0.  , -0.25, -0.25,  0.  ,  0.25,  0.25],
       [ 0.  , -0.5 ,  0.5 ,  0.  ,  0.  ,  0.  ,  0.  ,  0.5 , -0.5 ],
       [ 1.  ,  0.  , -1.  ,  0.  ,  0.  ,  0.  , -1.  ,  0.  ,  1.  ],
       [ 0.  ,  0.5 ,  0.5 ,  0.  ,  0.  ,  0.  ,  0.  , -0.5 , -0.5 ],
       [ 0.  ,  0.  ,  0.  ,  0.  , -0.25,  0.25,  0.  , -0.25,  0.25],
       [ 0.  ,  0.  ,  0.  ,  0.5 ,  0.  , -0.5 ,  0.5 ,  0.  , -0.5 ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.25,  0.25,  0.  ,  0.25,  0.25]])

In [149]:
Mi@M

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [150]:
M@f

array([f[0] + f[1] + f[2] + f[3] + f[4] + f[5] + f[6] + f[7] + f[8],
       -f[0] + f[2] - f[3] + f[5] - f[6] + f[8],
       f[0] + f[2] + f[3] + f[5] + f[6] + f[8],
       -f[0] - f[1] - f[2] + f[6] + f[7] + f[8],
       f[0] - f[2] - f[6] + f[8], -f[0] - f[2] + f[6] + f[8],
       f[0] + f[1] + f[2] + f[6] + f[7] + f[8],
       -f[0] + f[2] - f[6] + f[8], f[0] + f[2] + f[6] + f[8]],
      dtype=object)

In [151]:
sp.print_ccode(sp.factor(Mi@m))

/* Not supported in C: */
/* ImmutableDenseNDimArray */
[0.25*(m[4] - m[5] - m[7] + m[8]), -0.5*(m[3] - m[5] - m[6] + m[8]), -0.25*(m[4] + m[5] - m[7] - m[8]), -0.5*(m[1] - m[2] - m[7] + m[8]), 1.0*(m[0] - m[2] - m[6] + m[8]), 0.5*(m[1] + m[2] - m[7] - m[8]), -0.25*(m[4] - m[5] + m[7] - m[8]), 0.5*(m[3] - m[5] + m[6] - m[8]), 0.25*(m[4] + m[5] + m[7] + m[8])]


In [152]:
k = np.ndarray(9, dtype=object)
for i in range(9):
    k[i] = sp.Symbol(f'k[{i}]')
u, v = sp.symbols('u v')


In [153]:
K_ = np.ndarray((9,9), dtype=object)
for a in range(3):
    for b in range(3):
        for i in range(3):
            for j in range(3):
                if i != a:
                    K_[oid(a,b), oid(i,j)] = 0
                else:
                    K_[oid(a,b), oid(i,j)] = math.comb(b,j)*(-v)**(b-j)

K_

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [-v, 1, 0, 0, 0, 0, 0, 0, 0],
       [v**2, -2*v, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, -v, 1, 0, 0, 0, 0],
       [0, 0, 0, v**2, -2*v, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, -v, 1, 0],
       [0, 0, 0, 0, 0, 0, v**2, -2*v, 1]], dtype=object)

In [154]:
K = np.ndarray((9,9), dtype=object)
for a in range(3):
    for b in range(3):
        for i in range(3):
            for j in range(3):
                if j != b:
                    K[oid(a,b), oid(i,j)] = 0
                else:
                    K[oid(a,b), oid(i,j)] = math.comb(a,i)*(-u)**(a-i)

tmp = K@K_@m
for i in range(9):
    tmp[i] = sp.simplify(sp.collect(sp.collect(tmp[i], u), v))
tmp

array([m[0], -m[0]*v + m[1], m[0]*v**2 - 2*m[1]*v + m[2], -m[0]*u + m[3],
       -m[3]*v + m[4] + u*(m[0]*v - m[1]),
       m[3]*v**2 - 2*m[4]*v + m[5] - u*(m[0]*v**2 - 2*m[1]*v + m[2]),
       m[0]*u**2 - 2*m[3]*u + m[6],
       -m[6]*v + m[7] + u**2*(-m[0]*v + m[1]) + 2*u*(m[3]*v - m[4]),
       m[6]*v**2 - 2*m[7]*v + m[8] + u**2*(m[0]*v**2 - 2*m[1]*v + m[2]) - 2*u*(m[3]*v**2 - 2*m[4]*v + m[5])],
      dtype=object)

In [155]:
L_ = np.ndarray((9,9), dtype=object)
for a in range(3):
    for b in range(3):
        for i in range(3):
            for j in range(3):
                if i != a:
                    L_[oid(a,b), oid(i,j)] = 0
                else:
                    L_[oid(a,b), oid(i,j)] = math.comb(b,j)*(v)**(b-j)

In [156]:
L = np.ndarray((9,9), dtype=object)
for a in range(3):
    for b in range(3):
        for i in range(3):
            for j in range(3):
                if j != b:
                    L[oid(a,b), oid(i,j)] = 0
                else:
                    L[oid(a,b), oid(i,j)] = math.comb(a,i)*(u)**(a-i)

tmp = L@L_@k
for i in range(9):
    tmp[i] = sp.simplify(sp.collect(sp.collect(tmp[i], u), v))
tmp

array([k[0], k[0]*v + k[1], k[0]*v**2 + 2*k[1]*v + k[2], k[0]*u + k[3],
       k[3]*v + k[4] + u*(k[0]*v + k[1]),
       k[3]*v**2 + 2*k[4]*v + k[5] + u*(k[0]*v**2 + 2*k[1]*v + k[2]),
       k[0]*u**2 + 2*k[3]*u + k[6],
       k[6]*v + k[7] + u**2*(k[0]*v + k[1]) + 2*u*(k[3]*v + k[4]),
       k[6]*v**2 + 2*k[7]*v + k[8] + u**2*(k[0]*v**2 + 2*k[1]*v + k[2]) + 2*u*(k[3]*v**2 + 2*k[4]*v + k[5])],
      dtype=object)

In [157]:
L@L_@K@K_@m

array([m[0], m[1], m[2], m[3], m[4], m[5], m[6], m[7], m[8]], dtype=object)